### ISSUE TITLE
Weird problems on windows only

### ISSUE THREAD

**Issue by sckott** [phylocom/phylocom#25]
Using our R pkg `phylocomr` getting weird problems that seem to be only affecting windows OS 

e.g., with these taxa

```
euphorbiaceae/acalypha/acalypha_amblyodonta
euphorbiaceae/acalypha/acalypha_brasiliensis
euphorbiaceae/acalypha/acalypha_chorisandra
euphorbiaceae/acalypha/acalypha_claussenii
euphorbiaceae/acalypha/acalypha_communis
euphorbiaceae/acalypha/acalypha_digynostachya
euphorbiaceae/acalypha/acalypha_dimorpha
euphorbiaceae/acalypha/acalypha_diversifolia
euphorbiaceae/acalypha/acalypha_gracilis
euphorbiaceae/acalypha/acalypha_lagoensis
euphorbiaceae/acalypha/acalypha_macrostachya
```

And with tree `R20120829`

On my mac works fine, but on Windows it just fails. I would include error message, but I don't get any. Windows pops up with some thing about reporting to Microsoft, and no actual message. Anyway, any thoughts as to why this would blow up on Windows and not *nix platforms?

It's really weird because a subset of the taxa above works fine, e.g., the first 7 work fine, but then you do 1-8 and it blows up.

**Comment by sckott** [comment]
any thoughts on this @camwebb

**Comment by camwebb** [comment]
@sckott  I can't replicate this error. I don't have access to Windows, but using `wine` it runs fine:
```
Z:\home\cam\usr\phylocom-4.2\w32>phylomatic.exe -t taxa -f R20120829.new        ((acalypha_amblyodonta:0.333333,acalypha_brasiliensis:36.333336,acalypha_chorisandra:36.333336,acalypha_claussenii:36.333336,acalypha_communis:36.333336,acalypha_digynostachya:36.333336,acalypha_dimorpha:36.333336,acalypha_diversifolia:36.333336,acalypha_gracilis:36.333336,acalypha_lagoensis:36.333336,acalypha_macrostachya:36.333336)acalypha:21.666668)euphyllophyte;
```

**Comment by sckott** [comment]
okay, i'll look at it again
