### ISSUE TITLE
Faiths error

### ISSUE THREAD

**Issue by sckott** [phylocom/phylocom#26]
user reports https://github.com/ropensci/phylocomr/issues/18 an error with `pd()` using our R client. 

here's an example, get the two files in the linked issue above. 

```r
devtools::install_github("ropensci/phylocomr")
library("phylocomr")
ph_pd(sample = "sample.txt", phylo = "zanne.txt")
```

errors with

```r
Error: Program '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/phylocomr/bin//phylocom' terminated by SIGNAL (Segmentation fault: 11)
```

user reports near bottom of issue that a "cleaned" phylogeny (singletons removed i think) worked, but haven't checked it myself yet

Perhaps Phylocom can issue a better error message  if in fact this is about singleton nodes?

**Comment by sckott** [comment]
tried to locate error in Phylocom running R with valgrind but nothing useful from that

**Comment by daijiang** [comment]
Yes, the error message from Phylomatic is useless in 99% time.

**Comment by sckott** [comment]
@camwebb update on this: @daijiang  showed that PD works in this case

```r
veg <- read.table("https://github.com/ropensci/phylocomr/files/1053327/sample.txt")
veg$V3 <- tolower(veg$V3)
phylocomr::ph_pd(sample = veg, phylo = readLines("https://github.com/ropensci/phylocomr/files/1070084/zanne_phylocom.txt")[1]) 
```

but not this one

```r
tree1 <-  ape::collapse.singles(phytools::read.newick("https://github.com/ropensci/phylocomr/files/1070084/zanne_phylocom.txt"))
phylocomr::ph_pd(sample = veg, phylo = ape::write.tree(tree1))
```

i guess there are some singleton nodes that cause phylocom to crash  - any thoughts on why that's happening?

**Comment by camwebb** [comment]
Tracked this down. There were several scientific notation BLs inserted by `ape::collapse.singles()` (e.g., at  `eragrostis_echinochloidea:0.061613,):4e-06):0.02674,`). Phylocom cannot handle these. Other than this, both files run fine.

**Comment by sckott** [comment]
Ah, okay, so i suppose we need to somehow avoid scientific notation, will try that
