### ISSUE TITLE
Segmentation fault: 11 with Phylocom (Mac OS Catalina)

### ISSUE THREAD

**Issue by nicolaycunha** [phylocom/phylocom#33]
Hi, 

I do use Phylocom regularly and never have had much problems in generating and calibrating trees. Nevertheless, since the last update of the MacOS  Catalina, I simply can't make Phylocom to work. It happens with old files that I have already used for creating trees as new files. For using Phylocom in Catalina, I did recompile Phylocom using the source codes available at src folder. The error that appears is "Segmentation fault: 11".  Any clue on how to solve it is much appreciated. 

Cheers, 
Nicolay

**Comment by camwebb** [comment]
Does phylocom compile cleanly? If so please post a small example of a failing sample and tree file.

**Comment by nicolaycunha** [comment]
Yes, the pylocom compile cleanly. Actually, after the last Catalina update, everything seems to be working fine. I don't know the exact cause of such problem, but I am glad it is working fine now.
