### ISSUE TITLE
Segmentation problem with modified QIIME Silva tree

### ISSUE THREAD

**Issue by nouse123** [phylocom/phylocom#34]
[examples.zip](https://github.com/phylocom/phylocom/files/4443630/examples.zip)

I am using the Silva QIIME tree for phylogenetic null modelling :
```
phylo = read.tree("99_otus.tre") # from SILVA/QIIME
```
I then match the tree tips with the OTUs in my OTU table, and drop all unused tips.
```
match.phylo.otu = match.phylo.data(phylo, otu)
```
and proceed to write the tree to file:

```
library(ape)
ape::write.tree(match.phylo.otu$phy, "red_tree.tre")

plot_tree(match.phylo.otu$phy) #working
```
The tree has the following structure:
```
 match.phylo.otu$phy

Phylogenetic tree with 16326 tips and 16324 internal nodes.

Tip labels:
	DQ808717.1.1389, DQ798054.1.1390, DQ800502.1.1288, HQ767839.1.1406, DQ799856.1.1362, DQ798087.1.1390, ...
Node labels:
	, 0.927, 0.855, 0.824, 0.905, 0.440, ...

Unrooted; includes branch lengths.
```
I also have 16326 different OTUs in my table. 
When using this with phylocom on ubuntu command line, i am getting:
```
/phylocom comstruct -s ./../test.txt -f ./../test1_2.tre -m 0 -r 999 -a > test.out
Segmentation fault (core dumped)
```

What could be the problem? Thank you!
I am attaching tree and sample data, with two samples and ~4800 tips/OTUs.

**Comment by camwebb** [comment]
Your tree contains bootstrap values, which the phylocom Newick parser doesn't like. Remove them with regex: `)[0-9.]+`  to  `)`

**Comment by nouse123** [comment]
thank you very much.
in this case, instead of replacing the regex. i could use 
phyloseq_object$phy$node.label <- NULL # Erase the bootstrap values from the phylo object
and then write the tree to file.
