### ISSUE TITLE
bladj run-time error

### ISSUE THREAD

**Issue by snacktavish** [phylocom/phylocom#40]
Hi! I'm trying to run bladj on a very large tree. (94,000 tips, 5,000 calibrations). 
I am getting the error:
> Numerical Recipes run-time error...
> allocation failure 2 in matrix()
> ...now exiting to system...
> 

Any advice? Perhaps just too large of a tree?

**Comment by camwebb** [comment]
Yes, I guess it's just too big for the limits set by method/compiler/stack. The malloc() method is rather old (Numerical Recipes) and I'm sure there are fairly simple ways to rewrite the code to use more of the available RAM. Feel free to look into this if you are interested. I probably won't be fixing this soon though.

**Comment by camwebb** [comment]
Poking around a bit more, I guess the code is still valid... but with 94,000 tips there are up to `2^(log2(94,000)+1)-1` [nodes](https://en.wikipedia.org/wiki/Binary_tree#Properties_of_binary_trees) to be allocated (see [also](https://stackoverflow.com/questions/29886039/)), with several copies of each tree, each with assorted metadata. By my calculations, the numbers are in the MB range but not the GB range, so there should be memory available. But... this is relevant: <https://stackoverflow.com/a/3486163/563709>.

**Comment by snacktavish** [comment]
That all makes sense. I may take a crack at it, but more likely, I'll just split up or prune my tree! 
Thanks!
