### ISSUE TITLE
No output from nodesig

### ISSUE THREAD

**Issue by jamie-thompson** [phylocom/phylocom#41]
Hi, I have a large tree (11,000 tips) and binary trait data in the format:

`type	0
name	traitA
Pedicularis	1
Orthocarpus	1
Cordylanthus	1
Triphysaria	1
Clevelandia	1
Castilleja	1
Lamourouxia	1`

This is my command:

`phylocom.exe nodesig -f random_tree.tre -t random_nodesig_sample.txt`

I copied exactly the format of the example traits file, minus the other traits.  But it does not print anything, even though it pauses for a while seemingly computing.

**Comment by camwebb** [comment]
Answered by email: 

> There was scientific notation in some of the BLs. Cleaned version of
> tree attached. Plus nodesig needs community presence data in a _sample_
> file, not a traits file. But (an annoying gotcha, sorry) it also needs a
> dummy traits file. Files and oupput attached.
```bash
$ phylocom nodesig -f just_angio_pruned_tree.tre -s sample -t traits > jamie.nex
```
